# Generated by Django 5.0.7 on 2024-08-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_category_slug_alter_comment_email_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
